<?php

/**
 * ProcessWire Admin Actions.
 * by Adrian Jones
 *
 * ProcessWire 3.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ProcessAdminActions extends Process implements Module, ConfigurableModule {

    public static function getModuleInfo() {
        return array(
            'title' => 'Admin Actions',
            'summary' => 'Control panel for running various admin actions',
            'author' => 'Adrian Jones',
            'version' => 21,
            'singular' => true,
            'autoload' => false,
            'icon'     => 'cog',
            'nav' => array(
                array(
                    'url' => 'restore/',
                    'label' => 'Restore',
                    'icon' => 'reply',
                    'permission' => 'admin-actions-restore'
                )
            ),
            'page' => array(
                'name' => 'admin-actions',
                'parent' => 'setup',
                'title' => 'Admin Actions'
            ),
            // name of permission required of users to execute this Process
            'permission' => 'admin-actions',
            // automatically installed permissions
            'permissions' => array(
                'admin-actions' => 'Run selected AdminActions actions',
                'admin-actions-restore' => 'Run AdminActions restore feature'
            )
        );
    }


    /**
     * Data as used by the get/set functions
     *
     */
    protected $data = array();
    protected $actions = array();
    protected $hasPermission = false;
    protected $adminActionsCacheDir;
    protected $dbBackupFilename;
    protected $noPermissionMessage = 'Sorry, you do not have permission to use this action.';


   /**
     * Default configuration for module
     *
     */
    static public function getDefaultData() {
            return array(

            );
    }

    /**
     * Populate the default config data
     *
     */
    public function __construct() {
        foreach(self::getDefaultData() as $key => $value) {
            $this->$key = $value;
        }

        $this->adminActionsCacheDir = $this->config->paths->cache . 'AdminActions/';
        $this->dbBackupFilename = 'AdminActionsBackup.sql';
    }


    public function init() {
        parent::init();

        if($this->input->get->action) {
            if(count(array_intersect($this->data[$this->input->get->action]['roles'], $this->user->roles->each("id"))) !== 0) {
                require_once $this->getActionPath($this->input->get->action);
                $this->action = new $this->input->get->action;
                $this->hasPermission = true;
                $this->addHookAfter('Process::breadcrumb', $this, 'modifyBreadcrumb');
            }
            else {
                return $this->noPermissionMessage;
            }
        }

    }


    /**
     * Executed when root url for module is accessed
     *
     */
    public function ___execute() {
        $form = $this->buildSelectForm();
        if($this->input->post->submit) {
            return $this->processSelectForm($form);
        }
        else {
            return is_string($form) ? $form : $form->render();
        }
    }

    /**
     * Executed when ./options/ url for module is accessed
     *
     */
    public function ___executeOptions() {

        if(!$this->hasPermission) return $this->noPermissionMessage;

        $out = '<h2>'.$this->getActionName($this->action->className).'</h2>';

        if(method_exists($this->action,'checkRequirements') && !$this->action->checkRequirements()) {
            $out .= '<div class="adminActionsError"><p>Sorry, this action cannot proceed.</p><p>' . $this->action->requirementsMessage . '</p></div>';
        }
        else {
            $form = $this->buildOptionsForm();
            if(!$this->input->post->submit) {
                $out .= is_string($form) ? $form : $form->render();
            }
        }
        return $out;
    }

    /**
     * Executed when ./execute/ url for module is accessed
     *
     */
    public function ___executeExecute() {

        if(!$this->hasPermission) return $this->noPermissionMessage;

        $actionName = $this->getActionName($this->action->className);

        $actionTitle = '<h2>'.$actionName.'</h2>';

        $form = $this->buildOptionsForm();
        // build up $options array to pass to the action's executeAction method
        $options = array();
        // If the number of URL parameters (get) matches the number of required option fields in the form,
        // then we want to execute with the url parameters.
        // Note that the URL ($input->get) contains the additional "action", so start with $i=1
        $i=1;
        foreach($form->getAll() as $field) {
            if($field->hasClass('required')) $i++;
        }
        if(count($this->input->get) === $i) {
            $urlFields = new WireInputData();
            foreach($this->input->get as $field => $value) {
                // exclude fields that don't exist in the form, like the "action" url parameter
                if(!is_object($form->get($field)) || !$form->get($field)->parent) continue;
                // if field expects an array (multiple) then we need to convert the URL parameter
                if($form->get($field)->multiple) {
                    if(strpos($value, '|') !== false) {
                        $value = explode('|', $value);
                    }
                    else {
                        $value = array($value);
                    }
                }
                $urlFields[$field] = $value;
            }
            // disable CSRF because we are using GET data
            $form->protectCSRF = false;
            $form->processInput($urlFields);
            $form->protectCSRF = true;
            foreach($form->getAll() as $field) {
                $value = $form->get($field->name)->value;
                $options[$field->name] = $value;
            }
        }
        elseif(count($this->input->post) === 0) {
            return $actionTitle . '<p>Some required form options are missing.</p>';
        }
        else {
            $form->processInput($this->input->post);
            foreach($form->getAll() as $field) {
                $options[$field->name] = $form->get($field->name)->value;
            }
        }

        // backup database before executing action
        if (!file_exists($this->adminActionsCacheDir)) wireMkdir($this->adminActionsCacheDir);

        $backup = new WireDatabaseBackup($this->adminActionsCacheDir);
        $backup->setDatabase($this->database);
        $backup->setDatabaseConfig($this->config);
        $file = $backup->backup(array('filename' => $this->dbBackupFilename));

        $restoreDbCode =
        "<?php\n" .
        "if(file_exists('".$this->adminActionsCacheDir.$this->dbBackupFilename."')) {\n" .
            "\t\$db = new PDO('mysql:host={$this->config->dbHost};dbname={$this->config->dbName}', '{$this->config->dbUser}', '{$this->config->dbPass}');\n" .
            "\t\$sql = file_get_contents('" . $this->adminActionsCacheDir . $this->dbBackupFilename . "');\n" .
            "\t\$qr = \$db->query(\$sql);\n" .
        "}\n" .
        "if(isset(\$qr) && \$qr) {\n" .
            "\techo 'The database was successfully restored.';\n" .
        "}\n" .
        "else {\n" .
        "\techo 'Sorry, there was a problem and the database could not be restored.';\n" .
        "}";

        if(!file_put_contents($this->adminActionsCacheDir . 'restoredb.php', $restoreDbCode, LOCK_EX)) throw new WireException("Unable to write file: " . $this->adminActionsCacheDir . 'restoredb.php');

        // execute action and render output
        if($this->action->executeAction($options) && !$form->getErrors()) {
            $restoreLink = '<br /><div class="adminActionsWarning"><p>If you find a problem with the changes, you can <a href="./restore/">restore</a> the entire database.</p></div>';
            return $actionTitle . '<div class="adminActionsSuccess"><p>The '.$actionName.' action was completed successfully.</p><p>' . $this->action->successMessage . '</p></div>' . $restoreLink;
        }
        else {
            $this->error('Sorry, the '.$actionName.' action could not be completed successfully.');
            return $actionTitle . ($this->action->failureMessage ? '<div class="adminActionsError"><p>' . $this->action->failureMessage . '</p></div><br /><br />' : '') . $form->render();
        }

    }


    /**
     * Executed when ./restore/ url for module is accessed
     *
     */
    public function ___executeRestore() {
        if($this->user->isSuperuser() || $this->user->hasRole('admin-actions-restore')) {
            $backup = new WireDatabaseBackup($this->adminActionsCacheDir);
            $backup->setDatabase($this->database);
            $backup->setDatabaseConfig($this->config);

            $success = $backup->restore($this->adminActionsCacheDir.$this->dbBackupFilename);
            if($success) {
                $this->message("Database successfully restored.");
            }
            else {
                $this->error("Sorry, there was a problem and the database could not be restored.");
            }
            $this->session->redirect('../');
        }
        else {
            return 'Sorry, you do not have permission to run the restore feature.';
        }
    }


    /**
     * Build the Select form
     *
     */
    private function buildSelectForm() {

        $form = $this->modules->get("InputfieldForm");
        $form->name = 'select';
        $form->method = 'post';

        $f = wire('modules')->get("InputfieldMarkup");
        $f->attr('name', 'table');
        $table = wire('modules')->get("MarkupAdminDataTable");
        $table->setEncodeEntities(false);
        $table->setSortable(true);
        $table->setClass('adminactions');
        $table->headerRow(array(
            __('Title'),
            __('Description'),
            __('Notes'),
            __('Author')
        ));

        ksort($this->data);
        // get main actions in module folder
        $this->getActions(__DIR__ . '/actions', false);
        // get private actions from /site/templates/adminActions folder
        if(file_exists($customActionsDir = wire('config')->paths->templates.'AdminActions/')) {
            $this->getActions($customActionsDir, false);
        }
        // if more actions in folders than in config, display a warning
        if(count($this->actions) > count($this->data)) $this->error("You have new actions - please visit the module config settings, adjust approved roles, and click Submit to refresh this list.");

        $actionsCount=0;
        foreach($this->data as $action => $info) {
            if($this->getActionPath($action) && count(array_intersect($info['roles'], $this->user->roles->each("id"))) !== 0) {
                $row = array(
                    '<p><strong><a href="./options?action='.$action.'">'.$this->getActionName($action).'</a></strong></p>',
                    isset($info['description']) ? $info['description'] : '',
                    isset($info['notes']) ? '<span class="notes">'.$info['notes'].'</span>' : '',
                    isset($info['author']) ? '<span class="adminActionsAuthor">'.$info['author'].'<br />' . ($info['authorLinks'] ? $this->authorLinks($info['authorLinks']) : '') . '</span>' : '',

                );
                $table->row($row);
                $actionsCount++;
            }
        }
        $f->attr('value', $table->render());
        $form->add($f);

        if($actionsCount > 0) {
            return $form;
        }
        else {
            return 'Sorry, you do not have permission to run any actions.';
        }
    }

    /**
     * Process the action select form
     *
     */
    private function processSelectForm(InputfieldForm $form) {

        $form->processInput($this->input->post);
        if(count($form->getErrors())) {
            $this->error($form->getErrors());
            return $form->render();
        }
        else {
            $this->session->redirect('./options?action='.$form->get("action")->value);
        }

    }

    /**
     * Build the Options form
     *
     */
    private function buildOptionsForm() {

        $form = $this->modules->get("InputfieldForm");
        $form->name = 'options';
        $form->method = 'post';
        $form->action = './execute?action='.$this->action->className;

        $f = $this->modules->get("InputfieldMarkup");
        $f->name = 'details';
        $f->label = 'Details';
        $f->description = $this->action->description;
        $f->notes = $this->action->notes;
        $form->add($f);

        if($this->user->isSuperuser()) {
            $this->config->scripts->add($this->config->urls->siteModules . 'ProcessAdminActions/ace-editor/ace.js');
            $f = $this->modules->get("InputfieldMarkup");
            $f->name = 'actionCode';
            $f->label = 'Action Code';
            $f->description = 'This is the executeAction() method used by this action. This is just here as a reference in case you are curious what code is about to be executed.';
            $f->notes = 'The $options array contains the index (key) and value for each of the options defined below.';
            $f->value = '<div id="actionCodeViewer">'.$this->getFunctionCode($this->getActionPath($this->input->get->action), 'executeAction').'</div>';
            $f->collapsed = Inputfield::collapsedYes;
            $form->add($f);
        }

        if(method_exists($this->action,'defineOptions')) $form->add($this->action->defineOptions());

        $f = $this->modules->get("InputfieldSubmit");
        $f->name = 'submit';
        $f->value = 'Execute Action';
        $form->add($f);

        //preset any fields provided as URL parameters
        foreach($form->getAll() as $field) {
            if($fieldValue = $this->input->get($field->name)) {
                if (strpos($fieldValue, '|') !== false) $fieldValue = explode('|', $fieldValue);
                $form->get($field->name)->value = $fieldValue;
            }
        }

        return $form;
    }


    private function getActionPath($className) {
        if(file_exists($actionPath = __DIR__ . '/actions/'.$className.'.action.php')) {
            return $actionPath;
        }
        elseif(file_exists($actionPath = $this->config->paths->templates.'AdminActions/'.$className.'.action.php')) {
            return $actionPath;
        }
        else {
            return false;
        }
    }


    private function getActions($folderPath, $instantiate = true) {
        foreach(new \DirectoryIterator($folderPath) as $file) {
            if($file->isDot()) continue;
            if(substr($file->getBasename(), 0, 1) == '.') continue;
            if($file->isFile()) {
                $basename = $file->getBasename();
                if(!strpos($basename, '.action')) continue;
                if(!preg_match('/^([A-Z][a-zA-Z0-9_]+)\.action\.php$/', $basename, $matches)) continue;
                $className = $matches[1];
                if($instantiate) {
                    require_once $this->getActionPath($className);
                    $action = new $className;
                    $this->actions[$className]['description'] = $action->description;
                    $this->actions[$className]['notes'] = $action->notes;
                    $this->actions[$className]['author'] = $action->author;
                    $this->actions[$className]['authorLinks'] = $action->authorLinks;
                }
                $this->actions[$className]['name'] = $className;
            }
        }
    }

    private function authorLinks($authorLinks) {

        $pwIcon = '<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                 viewBox="0 0 39.7 40.1" enable-background="new 0 0 39.7 40.1" xml:space="preserve" width="20px" height="20px">
                    <g>
                        <path fill="none" stroke="#3A4163" stroke-width="4.2" stroke-miterlimit="10" d="M11.6,19.5"/>
                        <path fill="none" stroke="#3A4163" stroke-width="4.2" stroke-miterlimit="10" d="M11.8,22.4"/>
                        <linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="16.3309" y1="26.4008" x2="22.7901" y2="25.4266">
                            <stop  offset="0" style="stop-color:#AE3E7D"/>
                            <stop  offset="1" style="stop-color:#EA2262"/>
                        </linearGradient>
                        <path fill="url(#SVGID_1_)" d="M22.1,23.4c-0.6,0.5-1.2,0.7-1.6,0.8c-0.8,0.3-1.7,0.4-2.5,0.3c-0.1,0-0.2,0.1-0.3,0.2l-0.3,1.4
                            c-0.3,1.1,0.3,1.5,0.7,1.6c1.1,0.3,2.1,0.5,3.3,0.4c1.1-0.1,2.2-0.4,3.2-0.9l-1.9-4.5C22.5,23.1,22.3,23.3,22.1,23.4z"/>
                        <path fill="#EA2262" d="M39.3,15.8c-0.4-2.3-1.6-4.9-3-7c-1.2-1.8-3.2-3.9-5.2-5.2c-4.2-2.9-9-3.9-13.3-3.5c-4.5,0.5-8.3,2.2-11.4,5
                            C3.4,7.7,1.5,10.9,0.7,14c-0.9,3.1-0.7,5.9-0.4,8c0.3,2.2,1.4,4.9,1.4,4.9c0.2,0.5,0.5,0.7,0.7,0.8c0.8,0.4,2.1,0,3.1-1.2
                            c-0.3-1.1-0.4-2-0.5-2.6c-0.2-1.2-0.3-3.3-0.2-5.2c0.1-1,0.3-2.1,0.6-3.3c0.7-2.3,2.1-4.7,4.3-6.6c2.4-2.1,5.4-3.4,8.3-3.8
                            c1-0.1,3-0.2,5.3,0.3c0.5,0.1,2.6,0.7,4.9,2.2c1.7,1.1,3,2.6,3.9,3.9c1,1.3,2,3.6,2.3,5.2c0.4,1.9,0.4,3.9,0.1,5.8
                            c-0.4,1.9-1,3.8-2.1,5.5c-0.7,1.3-2.2,3-4,4.2c-1.6,1.1-3.4,2-5.3,2.4c-0.9,0.2-1.9,0.4-2.8,0.4c-0.8,0-2,0-2.8-0.1
                            c-1.2-0.2-1.4-0.5-1.7-0.9c0,0-0.2-0.3-0.2-1.1c0-7.4,0-5.4,0-9.2c0-1.1,0-2.1,0-2.9c0-1.5,0.2-2.5,1.2-3.5c0.7-0.8,1.8-1.3,2.9-1.3
                            c0.3,0,1.6,0,2.6,0.9c1.1,1,1.3,2.3,1.4,2.6c0.2,1.4-0.4,2.6-1,3.3c0.2,1.4,0.7,2.7,1.9,4.5c0.6-0.3,1.3-0.8,1.8-1.3
                            c1.3-1.2,2-2.7,2.3-4.4c0.3-1.9-0.1-3.9-0.9-5.6c-0.9-1.9-2.5-3.4-4.6-4.3c-2.1-0.8-3.8-0.9-6-0.3c-1.4,0.5-2.7,1.1-3.9,2.4
                            c-0.9,0.9-1.6,2-2,3.3c-0.4,1.3-0.5,2.2-0.6,3.7c0,1.1,0,2.1,0,3c0,1,0,2,0,3.1s0,2.1,0,3.1c0,2-0.1,2.3,0,3.3
                            c0,0.7,0.1,1.4,0.4,2.3c0.3,0.9,0.9,1.8,1.4,2.3c0.6,0.7,1.4,1.2,2.1,1.5c1.7,0.8,4.1,0.9,6,0.8c1.3,0,2.5-0.2,3.8-0.5
                            c2.5-0.6,4.9-1.7,7-3.2c2.3-1.6,4.2-3.8,5.3-5.7c1.4-2.2,2.3-4.7,2.8-7.2C39.9,20.9,39.8,18.3,39.3,15.8z"/>
                    </g>
                </svg>';

        $pwforumIcon = '<svg version="1.1" x="0px" y="0px" width="20px" height="20px" viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">
                            <path fill="#EA2262" d="M10,1.3C4.5,1.3,0,4.8,0,9.1c0,2,1,3.9,2.6,5.3c-0.1,1.3-0.3,3.2-1.3,4.1c1.9,0,3.9-1.2,5-2.1 c1.1,0.4,2.4,0.5,3.7,0.5c5.5,0,10-3.5,10-7.8S15.5,1.3,10,1.3z"/>
                        </svg>';

        $githubIcon = '<svg aria-hidden="true" class="octicon octicon-mark-github" height="20" version="1.1" viewBox="0 0 16 16" width="20"><path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path></svg>';

        $out = '';
        foreach($authorLinks as $resource => $link) {
            switch ($resource) {
                case 'pwdirectory':
                    $out .= ' <a href="http://directory.processwire.com/developers/'.$link.'/" title="ProcessWire developer profile">'.$pwIcon.'</a>';
                    break;
                case 'pwforum':
                    $out .= ' <a href="https://processwire.com/talk/profile/'.$link.'/" title="ProcessWire forum profile">'.$pwforumIcon.'</a>';
                    break;
                case 'github':
                    $out .= ' <a href="https://github.com/'.$link.'/" title="Github profile">'.$githubIcon.'</a>';
                    break;
            }
        }
        return $out;
    }


    private function getActionName($className) {
        return preg_replace('/(?<=\\w)(?=[A-Z])/'," $1", $className);
    }


    private function getFunctionCode($source, $functionName) {

        $tokens = token_get_all(file_get_contents($source));

        for($i=0,$z=count($tokens); $i<$z; $i++)
            if(is_array($tokens[$i])
                && $tokens[$i][0] == T_FUNCTION
                && is_array($tokens[$i+1])
                && $tokens[$i+1][0] == T_WHITESPACE
                && is_array($tokens[$i+2])
                && $tokens[$i+2][1] == $functionName)
                    break;

        $accumulator = array();
        // collect tokens from function head through opening brace
        while($tokens[$i] != '{' && ($i < $z)) {
            $accumulator[] = is_array($tokens[$i]) ? $tokens[$i][1] : $tokens[$i];
            $i++;
        }
        if($i == $z) {
            // handle error
        } else {
            // note, accumulate, and position index past brace
            $braceDepth = 1;
            $accumulator[] = '{';
            $i++;
        }
        while($braceDepth > 0 && ($i < $z)) {
            if(is_array($tokens[$i]))
                $accumulator[] = $tokens[$i][1];
            else {
                $accumulator[] = $tokens[$i];
                if($tokens[$i] == '{') $braceDepth++;
                else if($tokens[$i] == '}') $braceDepth--;
            }
            $i++;
        }
        return "\t".implode(null,$accumulator);
    }


    protected function modifyBreadcrumb($event) {
        $this->wire('breadcrumbs')->add(new Breadcrumb('./options?action='.$this->input->get->action, $this->getActionName($this->input->get->action)));
    }


    /**
     * Return an InputfieldsWrapper of Inputfields used to configure the class
     *
     * @param array $data Array of config values indexed by field name
     * @return InputfieldsWrapper
     *
     */
    public function getModuleConfigInputfields(array $data) {

        $data = array_merge(self::getDefaultData(), $data);

        $rolesOptions = array();
        foreach(wire('roles')->find("name!=guest") as $role) $rolesOptions[$role->id] = $role->name;

        $wrapper = new InputfieldWrapper();

        // get main actions in module folder
        $this->getActions(__DIR__ . '/actions/');
        // get private actions from /site/templates/adminActions folder
        if(file_exists($customActionsDir = wire('config')->paths->templates.'AdminActions/')) {
            $this->getActions($customActionsDir);
        }

        $f = wire('modules')->get("InputfieldMarkup");
        $f->name = 'instructions';
        $f->label = __('Choose roles that will be able to use each action');
        $f->description = __('Remember that the roles must also have the "admin-actions" permission to use this module at all.');
        $wrapper->add($f);

        foreach($this->actions as $action => $values) {
            $f = wire('modules')->get("InputfieldAsmSelect");
            $f->attr('name', $values['name']);
            $f->label = $this->getActionName($values['name']);
            $f->description = $values['description'];
            $f->notes = $values['notes'];
            $f->options = $rolesOptions;
            $f->columnWidth = 20;
            $f->setAsmSelectOption('sortable', false);
            $f->value = isset($data[$values['name']]['roles']) ? $data[$values['name']]['roles'] : array(wire('roles')->get('superuser')->id);
            $wrapper->add($f);

            // prepare initial superuser role for each action for initial module install
            $allData[$values['name']]['roles'] = array(wire('roles')->get('superuser')->id);
            // prepare initial description, notes, and author values
            $allData[$values['name']]['description'] = $values['description'];
            $allData[$values['name']]['notes'] = $values['notes'];
            $allData[$values['name']]['author'] = $values['author'];
            $allData[$values['name']]['authorLinks'] = $values['authorLinks'];
        }

        // save initial data when $data is empty on module install
        if(!$data) wire('modules')->saveModuleConfigData(wire('modules')->get("ProcessAdminActions"), $allData);

        // modify what is stored when settings saved so we can have the multidimensional array of data
        wire('modules')->addHookBefore('saveModuleConfigData', null, function($event) use ($allData) {
            $data = $event->arguments(1);
            foreach($data as $action => $roles) {
                if(isset($allData[$action])) $allData[$action]['roles'] = $roles;
            }
            $event->arguments(1, $allData);
        });

        return $wrapper;
    }

}
